# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "Destroying old data"

User.destroy_all

user_1 = User.create!(nickname: 'test', email: 'test@test.com', password: 'azerty')
user_2 = User.create!(nickname: 'test2', email: 'test2@test2.com', password: 'azerty')

post_1 = Post.create!(content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst quisque sagittis purus. Ornare massa eget egestas purus viverra accumsan in. Turpis in eu mi bibendum neque. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Turpis tincidunt id aliquet risus feugiat in. Id venenatis a condimentum vitae sapien. Varius morbi enim nunc faucibus a pellentesque sit amet. Dolor magna eget est lorem ipsum dolor. Magna fringilla urna porttitor rhoncus dolor purus. Faucibus nisl tincidunt eget nullam non nisi est. Quam nulla porttitor massa id neque aliquam. Fermentum odio eu feugiat pretium nibh ipsum consequat. Sed enim ut sem viverra aliquet eget. Sed blandit libero volutpat sed cras ornare arcu dui.
    In egestas erat imperdiet sed euismod. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Hendrerit gravida rutrum quisque non tellus orci. Proin sed libero enim sed faucibus turpis in eu. Egestas pretium aenean pharetra magna ac placerat vestibulum. Nibh mauris cursus mattis molestie a iaculis at erat. Purus non enim praesent elementum facilisis leo. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Eget nulla facilisi etiam dignissim diam quis. Integer quis auctor elit sed vulputate. Adipiscing commodo elit at imperdiet dui accumsan. Sed nisi lacus sed viverra tellus in. Egestas sed sed risus pretium quam vulputate dignissim. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Nec ultrices dui sapien eget mi. Molestie a iaculis at erat pellentesque adipiscing commodo.
    Dignissim sodales ut eu sem integer vitae justo eget magna. In vitae turpis massa sed elementum tempus egestas sed. Neque vitae tempus quam pellentesque nec nam aliquam sem et. Morbi leo urna molestie at elementum eu facilisis. Faucibus interdum posuere lorem ipsum. Viverra nam libero justo laoreet sit amet. Quisque egestas diam in arcu cursus euismod. Accumsan tortor posuere ac ut consequat. Volutpat diam ut venenatis tellus. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Neque laoreet suspendisse interdum consectetur libero. Magna ac placerat vestibulum lectus. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Nulla facilisi etiam dignissim diam quis. Pharetra et ultrices neque ornare aenean euismod elementum nisi.
    Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Arcu dictum varius duis at consectetur lorem donec massa. Urna neque viverra justo nec ultrices dui. A diam sollicitudin tempor id eu nisl nunc mi. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Faucibus vitae aliquet nec ullamcorper sit. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Ipsum dolor sit amet consectetur adipiscing elit ut. Et malesuada fames ac turpis egestas maecenas pharetra. Facilisi cras fermentum odio eu feugiat. Amet venenatis urna cursus eget nunc scelerisque viverra. Metus dictum at tempor commodo ullamcorper a lacus. Sit amet dictum sit amet justo donec enim. Dui faucibus in ornare quam viverra orci sagittis. Sed viverra tellus in hac habitasse platea dictumst vestibulum.
    Convallis posuere morbi leo urna molestie at elementum eu. Neque laoreet suspendisse interdum consectetur libero. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Morbi tristique senectus et netus et malesuada fames. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Nibh tortor id aliquet lectus proin nibh nisl condimentum. At erat pellentesque adipiscing commodo elit at imperdiet. Purus faucibus ornare suspendisse sed nisi lacus sed. Odio morbi quis commodo odio aenean sed.", url:"https://en.wikipedia.org/wiki/Indonesia", title:"Indonesia, the temple, the food, the rain", user: user_1)
post_2 = Post.create!(content: "A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. A very large 2nd post. ", url:"gfd", title:"test number 2", user: user_1)
post_3 = Post.create!(content: "A small post", url:"gfd", title:"test the 3rd", user: user_1)
post_4 = Post.create!(content: "ybdrgergreggergergegegegegetre", url:"gfd", title:"final of all tests", user: user_1)

comment_1 = Comment.create!(user: user_2, post: post_1, content: "that is the test 1st comment for the 1st test post")
comment_2 = Comment.create!(user: user_2, post: post_1, content: "that is the test 2nd comment for the 1st test post")
comment_3 = Comment.create!(user: user_2, post: post_1, content: "that is the test 3rd comment for the 1st test post")
comment_4 = Comment.create!(user: user_2, post: post_1, content: "that is the test 4th comment for the 1st test post")